/* SPDX-License-Identifier: MIT
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_MSTR_IF_DUP_CRDT_REGS_H_
#define ASIC_REG_MSTR_IF_DUP_CRDT_REGS_H_

/*
 *****************************************
 *   MSTR_IF_DUP_CRDT
 *   (Prototype: RTR_CRDT_DUP)
 *****************************************
 */

#define mmMSTR_IF_DUP_CRDT_CRDT_EN 0x0

#define mmMSTR_IF_DUP_CRDT_RTR_CRDT_SIZE_0 0x4

#define mmMSTR_IF_DUP_CRDT_RTR_CRDT_SIZE_1 0x8

#define mmMSTR_IF_DUP_CRDT_RTR_CRDT_SIZE_2 0xC

#define mmMSTR_IF_DUP_CRDT_RTR_CRDT_SIZE_3 0x10

#define mmMSTR_IF_DUP_CRDT_RTR_CRDT_SIZE_4 0x14

#define mmMSTR_IF_DUP_CRDT_RTR_CRDT_SIZE_5 0x18

#define mmMSTR_IF_DUP_CRDT_RTR_CRDT_SIZE_6 0x1C

#define mmMSTR_IF_DUP_CRDT_RTR_CRDT_SIZE_7 0x20

#define mmMSTR_IF_DUP_CRDT_RTR_CRDT_SIZE_8 0x24

#define mmMSTR_IF_DUP_CRDT_RTR_CRDT_SIZE_9 0x28

#define mmMSTR_IF_DUP_CRDT_RTR_CRDT_SIZE_10 0x2C

#define mmMSTR_IF_DUP_CRDT_RTR_CRDT_SIZE_11 0x30

#define mmMSTR_IF_DUP_CRDT_RTR_CRDT_SIZE_12 0x34

#define mmMSTR_IF_DUP_CRDT_RTR_CRDT_SIZE_13 0x38

#define mmMSTR_IF_DUP_CRDT_RTR_CTR_CNT_0 0x3C

#define mmMSTR_IF_DUP_CRDT_RTR_CTR_CNT_1 0x40

#define mmMSTR_IF_DUP_CRDT_RTR_CTR_CNT_2 0x44

#define mmMSTR_IF_DUP_CRDT_RTR_CTR_CNT_3 0x48

#define mmMSTR_IF_DUP_CRDT_RTR_CTR_CNT_4 0x4C

#define mmMSTR_IF_DUP_CRDT_RTR_CTR_CNT_5 0x50

#define mmMSTR_IF_DUP_CRDT_RTR_CTR_CNT_6 0x54

#define mmMSTR_IF_DUP_CRDT_RTR_CTR_CNT_7 0x58

#define mmMSTR_IF_DUP_CRDT_RTR_CTR_CNT_8 0x5C

#define mmMSTR_IF_DUP_CRDT_RTR_CTR_CNT_9 0x60

#define mmMSTR_IF_DUP_CRDT_RTR_CTR_CNT_10 0x64

#define mmMSTR_IF_DUP_CRDT_RTR_CTR_CNT_11 0x68

#define mmMSTR_IF_DUP_CRDT_RTR_CTR_CNT_12 0x6C

#define mmMSTR_IF_DUP_CRDT_RTR_CTR_CNT_13 0x70

#define mmMSTR_IF_DUP_CRDT_RTR_CTR_SET_EN_0 0x74

#define mmMSTR_IF_DUP_CRDT_RTR_CTR_SET_EN_1 0x78

#define mmMSTR_IF_DUP_CRDT_RTR_CTR_SET_EN_2 0x7C

#define mmMSTR_IF_DUP_CRDT_RTR_CTR_SET_EN_3 0x80

#define mmMSTR_IF_DUP_CRDT_RTR_CTR_SET_EN_4 0x84

#define mmMSTR_IF_DUP_CRDT_RTR_CTR_SET_EN_5 0x88

#define mmMSTR_IF_DUP_CRDT_RTR_CTR_SET_EN_6 0x8C

#define mmMSTR_IF_DUP_CRDT_RTR_CTR_SET_EN_7 0x90

#define mmMSTR_IF_DUP_CRDT_RTR_CTR_SET_EN_8 0x94

#define mmMSTR_IF_DUP_CRDT_RTR_CTR_SET_EN_9 0x98

#define mmMSTR_IF_DUP_CRDT_RTR_CTR_SET_EN_10 0x9C

#define mmMSTR_IF_DUP_CRDT_RTR_CTR_SET_EN_11 0xA0

#define mmMSTR_IF_DUP_CRDT_RTR_CTR_SET_EN_12 0xA4

#define mmMSTR_IF_DUP_CRDT_RTR_CTR_SET_EN_13 0xA8

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_EN_0 0xAC

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_EN_1 0xB0

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_EN_2 0xB4

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_EN_3 0xB8

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_EN_4 0xBC

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_EN_5 0xC0

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_EN_6 0xC4

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_EN_7 0xC8

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_EN_8 0xCC

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_EN_9 0xD0

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_EN_10 0xD4

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_EN_11 0xD8

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_EN_12 0xDC

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_EN_13 0xE0

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_ST_ADDR_0 0xE4

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_ST_ADDR_1 0xE8

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_ST_ADDR_2 0xEC

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_ST_ADDR_3 0xF0

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_ST_ADDR_4 0xF4

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_ST_ADDR_5 0xF8

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_ST_ADDR_6 0xFC

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_ST_ADDR_7 0x100

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_ST_ADDR_8 0x104

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_ST_ADDR_9 0x108

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_ST_ADDR_10 0x10C

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_ST_ADDR_11 0x110

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_ST_ADDR_12 0x114

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_ST_ADDR_13 0x118

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_END_ADDR_0 0x11C

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_END_ADDR_1 0x120

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_END_ADDR_2 0x124

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_END_ADDR_3 0x128

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_END_ADDR_4 0x12C

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_END_ADDR_5 0x130

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_END_ADDR_6 0x134

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_END_ADDR_7 0x138

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_END_ADDR_8 0x13C

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_END_ADDR_9 0x140

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_END_ADDR_10 0x144

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_END_ADDR_11 0x148

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_END_ADDR_12 0x14C

#define mmMSTR_IF_DUP_CRDT_CRED_TAR_END_ADDR_13 0x150

#define mmMSTR_IF_DUP_CRDT_RAZWI_ERR_RESP 0x154

#define mmMSTR_IF_DUP_CRDT_AW_RAZWI_HAPPENED_CLR 0x158

#define mmMSTR_IF_DUP_CRDT_AW_RAZWI_HAPPENED_ST 0x15C

#define mmMSTR_IF_DUP_CRDT_RAZWI_AWADDR 0x160

#define mmMSTR_IF_DUP_CRDT_RAZWI_AWID 0x164

#endif /* ASIC_REG_MSTR_IF_DUP_CRDT_REGS_H_ */
