#pragma once

#include <set>
#include <string_view>

static const std::set<std::string_view>& getAllowedForStitchingList()
{
    static std::set<std::string_view> stitchableList = {"abs_fwd",
                                                   "add",
                                                   "add_fwd",
                                                   "batch_norm_inf",
                                                   "batch_norm_stage1_bwd",
                                                   "batch_norm_stage1_fwd",
                                                   "batch_norm_stage2_add_relu_bwd",
                                                   "batch_norm_stage2_add_relu_fwd",
                                                   "batch_norm_stage2_bwd",
                                                   "batch_norm_stage2_fwd",
                                                   "batch_norm_stage2_relu_bwd",
                                                   "batch_norm_stage2_relu_fwd",
                                                   "cast",
                                                   "constant",
                                                   "cos",
                                                   "cos_fwd",
                                                   "div",
                                                   "div_fwd",
                                                   "dropout_bwd",
                                                   "equal",
                                                   "equal_fwd",
                                                   "exp",
                                                   "exp_fwd",
                                                   "gelu_bwd",
                                                   "gelu_fwd",
                                                   "isinf_fwd",
                                                   "isnan",
                                                   "isnan_fwd",
                                                   "leakyrelu",
                                                   "leakyrelu_fwd",
                                                   "log",
                                                   "log_fwd",
                                                   "max",
                                                   "max_fwd",
                                                   "memcpy",
                                                   "min",
                                                   "min_fwd",
                                                   "mod",
                                                   "mult",
                                                   "mult_fwd",
                                                   "neg",
                                                   "neg_fwd",
                                                   "reciprocal",
                                                   "reciprocal_fwd",
                                                   "relu",
                                                   "relu_bwd",
                                                   "relu_fwd",
                                                   "rsqrt",
                                                   "rsqrt_fwd",
                                                   "sigmoid",
                                                   "sigmoid_fwd",
                                                   "sin",
                                                   "sin_fwd",
                                                   "softmax_bwd",
                                                   "sqrt",
                                                   "sqrt_fwd",
                                                   "sub",
                                                   "sub_fwd",
                                                   "tanh",
                                                   "tanh_bwd",
                                                   "tanh_fwd",
                                                   "nop"};
    return stitchableList;
}