import os

BACK_PRESSURE_THRESHOLD = 50000
PARTIAL_WRITES_THRESHOLD = 4000

BACK_PRESSURE_EVENT_NAME = '[8] Back pressure from memory to TPC write queue on store tensors'
PARTIAL_WRITES_EVENT_NAME = 'Outgoing HBM partial writes'
OUTGOING_MEM_WRITE_REQUESTS_EVENT_NAME = "Outgoing mem_write requests"
TPC_VALUE = 'TPC'
END_OF_WRITE_EVENT_DESCIPTION = 'TPC_END_OF_KERNEL_MESSAGE_WRITE'
TPC_SPU_START_EVENT_DESCRIPTION = 'TPC_SPU_START'
TPC_SPU_START_TO_SPU_HALT_EVENT_DESCRIPTION = 'TPC_SPU_START_TO_SPU_HALT'

HALT_EVENT_DESCRIPTION = 'TPC_VPU_HALT'

LOG_INFO_PARTIAL_INFO_KEY = 'info'
LOG_INFO_CACHE_WARMUP_NODE_NAMES = 'warmup'

RUN_1_DIR = 'PARTIALS_WRITES_DEBUG_AVOID_HANDLING_IN_FINAL_GRAPH=True'
RUN_2_DIR = 'PARTIALS_WRITES_DEBUG_AVOID_HANDLING_IN_FINAL_GRAPH=False'
TRACE_DIR = os.path.join('trace','hw')
LOG_DIR = 'logs-compile'
LOG_SUFFIX = '_graph_compiler.log'

OUTPUT_SUFFIX_RUN_1 = 'f'
OUTPUT_SUFFIX_RUN_2 = 't'

MULTIPROCESSING_NUM_PROCESSES = 8