ENUM_TXT_COL(LaunchUser,                                  "synLaunch Total time(ns)"                      )
ENUM_TXT_COL(seqId,                                       "seqId"                                         )
ENUM_TXT_COL(recipeId,                                    "recipeId"                                      )
ENUM_TXT_COL(recipeSuccessfulRuns,                        "successfulRuns"                                )
ENUM_TXT_COL(LaunchSubmit,                                "LaunchSubmit"                                  )
ENUM_TXT_COL(memcpyAsyncLaunch,                           "memcpyAsyncLaunch"                             )
ENUM_TXT_COL(memcpyAsyncLaunchSubmit,                     "memcpyAsyncLaunchSubmit"                       )
ENUM_TXT_COL(StreamWaitEventLaunchSubmit,                 "StreamWaitLaunchSubmit"                        )
ENUM_TXT_COL(EventRecordLaunchSubmit,                     "EventRecordLaunchSubmit"                       )
ENUM_TXT_COL(memcpyAsyncUser,                             "memcpyAsyncUser"                               )
ENUM_TXT_COL(memcpyAsyncUserSubmit,                       "memcpyAsyncUserSubmit"                         )
ENUM_TXT_COL(StreamWaitEventUser,                         "StreamWaitUser"                                )
ENUM_TXT_COL(StreamWaitEventUserSubmit,                   "StreamWaitUserSubmit"                          )
ENUM_TXT_COL(synEventRecordUser,                          "EventRecordUser"                               )
ENUM_TXT_COL(synEventRecordUserSubmit,                    "EventRecordUserSubmit"                         )
ENUM_TXT_COL(waitForCs,                                   "waitForCs launch (ns)"                         )
ENUM_TXT_COL(ctx_queue_full_drop_cnt,                     "Driver CS queue full"                          )
ENUM_TXT_COL(devicePrepareLaunch,                         "Device prepare launch (ns)"                    )
ENUM_TXT_COL(deviceMutexDuration,                         "DeviceMutexDuration (ns)"                      )
ENUM_TXT_COL(recipeInit,                                  "recipe Init (ns)"                              )
ENUM_TXT_COL(csdcStreamCopyAllocate,                      "csdcStreamCopyAllocate"                        )
ENUM_TXT_COL(csdcStreamCopyRelease,                       "csdcStreamCopyRelease"                         )
ENUM_TXT_COL(csdcStreamComputeAllocate,                   "csdcStreamComputeAllocate"                     )
ENUM_TXT_COL(csdcStreamComputeRelease,                    "csdcStreamComputeRelease"                      )
ENUM_TXT_COL(dataChunkCacheAlloc,                         "DataChunksCacheAlloc"                          )
ENUM_TXT_COL(dataChunkCacheCreated,                       "DataChunksCacheCreated"                        )
ENUM_TXT_COL(dataChunkCacheReleased,                      "DataChunksCacheRelease"                        )
ENUM_TXT_COL(dataChunkCacheDestruct,                      "DataChunksCacheDestruct"                       )
ENUM_TXT_COL(usedDataChunks,                              "UsedDataChunks"                                )
ENUM_TXT_COL(freeDataChunks,                              "FreeChunks"                                    )
ENUM_TXT_COL(csdcDbSize,                                  "csdcDbSize"                                    )
ENUM_TXT_COL(tensorsAnalyze,                              "TensorsAnalyze(ns)"                            )
ENUM_TXT_COL(tensorsValidate,                             "tensorsValidate(ns)"                           )
ENUM_TXT_COL(patchingAll,                                 "Patching time(ns)"                             )
ENUM_TXT_COL(csdcFullReuse,                               "csdcFullReuse"                                 )
ENUM_TXT_COL(csdcPartialReuse,                            "csdcPartialReuse"                              )
ENUM_TXT_COL(query,                                       "query (ns)"                                    )
ENUM_TXT_COL(inFlightLaunchReqStart,                      "inFlightLaunchReqStart"                        )
ENUM_TXT_COL(inFlightLaunchReqLeft,                       "inFlightLaunchReqLeft"                         )
ENUM_TXT_COL(patchDynamicRecipe,                          "patchDynamicRecipe (ns)"                       )
ENUM_TXT_COL(downloadPrgData,                             "downloadProgramDataToDev(ns)"                  )
ENUM_TXT_COL(downloadPrgCode,                             "downloadPrgCode (ns)"                          )
ENUM_TXT_COL(staticBlobsCache,                            "staticBlobsCache (ns)"                         )
ENUM_TXT_COL(dataCache,                                   "dataCache (ns)"                                )
ENUM_TXT_COL(patchableCache,                              "patchableCache (ns)"                           )
ENUM_TXT_COL(streamDbMutexDuration,                       "streamDbMutexDuration (ns)"                    )
ENUM_TXT_COL(streamCopyMemCopyDuration,                   "streamCopyMemCopyDuration(ns)"                 )
ENUM_TXT_COL(streamCopyMutexDuration,                     "streamCopyMutexDuration (ns)"                  )
ENUM_TXT_COL(streamCopyOperationDuration,                 "streamCopyOperationDuration(ns)"               )
ENUM_TXT_COL(streamCopyRetrieveCsDc,                      "streamCopyRetrieveCsDc (ns)"                   )
ENUM_TXT_COL(streamCopySubmit,                            "streamCopySubmit (ns)"                         )
ENUM_TXT_COL(streamCopySubmitPrepare,                     "streamCopySubmitPrepare (ns)"                  )
ENUM_TXT_COL(streamCopySubmitExecute,                     "streamCopySubmitExecute (ns)"                  )
ENUM_TXT_COL(wcmObserverDbMutexDuration,                  "wcmObserverDbMutexDuration(ns)"                )
ENUM_TXT_COL(wcmObserverWaitDuration,                     "wcmObserverWaitDuration(ns)"                   )
ENUM_TXT_COL(wcmAddDuration,                              "wcmAddDuration(ns)"                            )
ENUM_TXT_COL(wcmQueryDurationFail,                        "wcmQueryDurationFail(ns)"                      )
ENUM_TXT_COL(wcmQueryDurationTimeout,                     "wcmQueryDurationTimeout(ns)"                   )
ENUM_TXT_COL(wcmQueryDurationComplete,                    "wcmQueryDurationComplete(ns)"                  )
ENUM_TXT_COL(dipGetCommandsBufferDataChunks,              "dipGetCommandsBufferDataChunks (ns)"           )
ENUM_TXT_COL(dipRecipeActivate,                           "dipRecipeActivate (ns)"                        )
ENUM_TXT_COL(dipRecipeEnqueue,                            "dipRecipeEnqueue (ns)"                         )
ENUM_TXT_COL(dipAnalyzeNewTensors,                        "dipAnalyzeNewTensors (ns)"                     )
ENUM_TXT_COL(dipSendCommandSubmission,                    "dipSendCommandSubmission(ns)"                  )
ENUM_TXT_COL(dipCopyPrgToDc,                              "dipCopyPrgToDc (ns)"                           )
ENUM_TXT_COL(dipCopyPatchableBlobs,                       "dipCopyPatchableBlobs (ns)"                    )
ENUM_TXT_COL(streamComputeLaunch,                         "queueComputeLaunch (ns)"                      )
ENUM_TXT_COL(streamComputeMutexDuration,                  "queueComputeMutexDuration (ns)"               )
ENUM_TXT_COL(streamComputeSync,                           "queueComputeSync (ns)"                        )
ENUM_TXT_COL(streamComputeActivate,                       "queueComputeActivate (ns)"                    )
ENUM_TXT_COL(streamComputeEnqueueAndSync,                 "queueComputeEnqueueAndSync (ns)"              )
ENUM_TXT_COL(streamComputeEnqueue,                        "queueComputeEnqueue (ns)"                     )
ENUM_TXT_COL(streamComputeEnqueueUpdatePostExecution,     "queueComputeEnqueueUpdatePostExecution (ns)"  )
ENUM_TXT_COL(streamComputeReserve,                        "queueComputeReserve (ns)"                     )
ENUM_TXT_COL(streamComputeUnreserve,                      "queueComputeUnreserve (ns)"                   )
ENUM_TXT_COL(streamComputeEventManipulation,              "queueComputeEventManipulation (ns)"           )
ENUM_TXT_COL(streamComputeRetrieveCsDc,                   "queueComputeRetrieveCsDc(ns)"                 )
ENUM_TXT_COL(streamComputeRetrieveCsDcRelease,            "queueComputeRetrieveCsDcRelease(ns)"          )
ENUM_TXT_COL(streamComputeRetrieveCsDcAcquire,            "queueComputeRetrieveCsDcAcquire(ns)"          )
ENUM_TXT_COL(streamComputeRetrieveCsDcWcm,                "queueComputeRetrieveCsDcWcm(ns)"              )
ENUM_TXT_COL(streamComputePartialReuse,                   "queueComputePartialReuse"                     )
ENUM_TXT_COL(StreamLockEventWaitDuration,                 "StreamLockEventWaitDuration")
ENUM_TXT_COL(StreamLockExistingJobWaitingDuration,        "StreamLockExistingJobWaitingDurati  on")
ENUM_TXT_COL(StreamLockAffinityDuration,                  "StreamLockAffinityDuration")
ENUM_TXT_COL(StreamLockBusyDuration,                      "StreamLockBusyDuration")
ENUM_TXT_COL(StreamAddJob,                                "StreamAddJob")
ENUM_TXT_COL(StreamSynchronize,                           "StreamSynchronize")
ENUM_TXT_COL(StreamQuery,                                 "StreamQuery")
ENUM_TXT_COL(createStaticDma,                             "createStaticCPdma (ns)"                        )
ENUM_TXT_COL(calcDcNum,                                   "calcDcNum (ns)"                                )
ENUM_TXT_COL(calcBlobDeviceAddr,                          "calcBlobDeviceAddr (ns)"                       )
ENUM_TXT_COL(downloadProgramCodeBlobs,                    "downloadProgramCodeBlobs (ns)"                 )
ENUM_TXT_COL(waitForSyncSynDmaDown,                       "waitForSyncSynDmaDown (ns)"                    )

ENUM_TXT_COL(dcSizeCpDma,                                 "dcSizeCpDma"                                   )
ENUM_TXT_COL(dcAmountCpDmaCached,                         "dcAmountCpDmaCached"                           )
ENUM_TXT_COL(dcAmountCpDmaNotCached,                      "dcAmountCpDmaNotCached"                        )
ENUM_TXT_COL(maxProgramDcSizeCached,                      "maxProgramDcSizeCached"                        )
ENUM_TXT_COL(maxProgramDcSizeNotCached,                   "maxProgramDcSizeNotCached"                     )
ENUM_TXT_COL(maxProgramWcDcSizeCached,                    "maxProgramWcDcSizeCached"                      )
ENUM_TXT_COL(maxProgramWcDcSizeNotCached,                 "maxProgramWcDcSizeNotCached"                   )
ENUM_TXT_COL(avgProgramDcSizeCached,                      "avgProgramDcSizeCached"                        )
ENUM_TXT_COL(avgProgramDcSizeNotCached,                   "avgProgramDcSizeNotCached"                     )
ENUM_TXT_COL(avgProgramWcDcSizeCached,                    "avgProgramWcDcSizeCached"                      )
ENUM_TXT_COL(avgProgramWcDcSizeNotCached,                 "avgProgramWcDcSizeNotCached"                   )

ENUM_TXT_COL(dcSizeCommand,                               "dcSizeCommand"                                 )
ENUM_TXT_COL(dcAmountCommand,                             "dcAmountCommand"                               )
ENUM_TXT_COL(accumulateBlobsChunksSize,                   "accumulateBlobsChunksSize"                     )

ENUM_TXT_COL(nonPatchableAlreadyIn,                       "RCnonPatchableAlreadyIn"                       )
ENUM_TXT_COL(prgDataAlreadyIn,                            "RCprgDataAlreadyIn"                            )
ENUM_TXT_COL(recipeCacheNoMemory,                         "RCrecipeCacheNoMemory"                         )
ENUM_TXT_COL(allocatedNonPatchable,                       "RCallocatedNonPatchable"                       )
ENUM_TXT_COL(allocatedPrgData,                            "RCallocatedPrgData"                            )
ENUM_TXT_COL(RecipeCacheFreeMemory,                       "RCRecipeCacheFreeMemory"                       )
ENUM_TXT_COL(recipeCacheNoMemoryAfterFree,                "RCNoMemoryAfterFree"                           )
ENUM_TXT_COL(recipeCacheUniqueReUse,                      "RCUniqueReUse"                                 )

ENUM_TXT_COL(initDynamicRecipe,                           "initDynamicRecipe (ns)"                        )
ENUM_TXT_COL(DsdPatchDynamicRecipe,                       "DsdPatchDynamicRecipe (ns)"                    )
ENUM_TXT_COL(DsdShapeTensors,                             "DsdShapeTensors"                               )
ENUM_TXT_COL(DsdPP,                                       "DsdPP"                                         )
ENUM_TXT_COL(DsdBypass,                                   "DsdBypass (bypass=true)"                       )
ENUM_TXT_COL(DsdSkipPP,                                   "DsdSkipPP (skipped rois)"                      )
ENUM_TXT_COL(DsdInitRecipe,                               "DsdInitRecipe (phase) (ns)"                    )
ENUM_TXT_COL(DsdInitTensors,                              "DsdInitTensors (phase) (ns)"                   )
ENUM_TXT_COL(DsdSif,                                      "DsdSif (SIF phase)"                            )
ENUM_TXT_COL(DsdSmf,                                      "DsdSmf (SMF phase)"                            )
ENUM_TXT_COL(DsdSVerifyOutputs,                           "DsdSVerifyOut (verify phase)"                  )

ENUM_TXT_COL(DsdNoPatch,                                  "DsdNoPatch (PP size=0)"                        )
ENUM_TXT_COL(DsdSifOnly,                                  "DsdSifTime (only sif)"                         )
ENUM_TXT_COL(DsdSmfOnly,                                  "DsdSmfTime (only smf)"                         )

ENUM_TXT_COL(scalMemcpy2Mapped,                           "scalMemcpy2Mapped (ns)"                        )
ENUM_TXT_COL(ih2dBufferMemAlloc,                          "ih2dBufferMemAlloc (ns)"                       )
ENUM_TXT_COL(scalPdmaDownload,                            "scalPdmaDownload (ns)"                         )
ENUM_TXT_COL(scalEnqueue,                                 "scalEnqueue (ns)"                              )
ENUM_TXT_COL(CompletionNeedResources,                     "CompletionNeedResources"                       )

ENUM_TXT_COL(scalSubmit,                                  "scalSubmit (ns)"                               )
ENUM_TXT_COL(scalSubmitCompute,                           "scalSubmitCompute (ns)"                        )
ENUM_TXT_COL(scalGetMapped,                               "scalGetMapped (ns)"                            )
ENUM_TXT_COL(scalGetHbms,                                 "scalGetHbms (ns)"                              )
ENUM_TXT_COL(scalChkCompletion,                           "scalChkCompletion"                             )
ENUM_TXT_COL(mappedOutBits,                               "mappedOutBits NP/P (1/2)"                      )
ENUM_TXT_COL(mmmCouldNotRelease,                          "mmmCouldNotRelease"                            )
ENUM_TXT_COL(mmmReleasedEntry,                            "mmmReleasedEntry"                              )
ENUM_TXT_COL(mmmReleasedSegment,                          "mmmReleasedSegment"                            )
ENUM_TXT_COL(ccbBusyTime,                                 "ccbBusyTime"                                   )
ENUM_TXT_COL(scalHbmSingleBuff,                           "scalHbmSingleBuff"                             )

ENUM_TXT_COL(colLast,                                     "last and invalid"                              )
