//
// Created by esdeor on 11/22/22.
//
#pragma once

enum class StatApiPoints
{
    synLaunchP,
    synLaunchWithExternalEventsP,
    synStreamWaitEventP,
    synStreamQueryP,
    synEventCreateP,
    synEventDestroyP,
    synEventRecordP,
    synEventQueryP,
    synEventElapsedTimeP,
    synEventMapTensorP,
    synTensorExtExtractExecutionOrderP,
    synRecipeDestroyP,
    synRecipeGetAttributeP,
    synSectionCreateP,
    synSectionSetGroupP,
    synSectionGetGroupP,
    synSectionGetPersistentP,
    synSectionSetPersistentP,
    synSectionSetConstP,
    synSectionGetConstP,
    synSectionDestroyP,
    synWorkspaceGetSizeP,
    synMemCopyAsyncMultipleP,
    synMemCopyAsyncP,
    synTensorCreateP,
    synConstTensorCreateP,
    synTensorRetrieveIdsP,
    synTensorDestroyP,
    synNodeCreateP,
    synNodeCreateWithIdP,
    synNodeTypeSetPrecisionP,
    synNodeDependencySetP,
    synNodeSetDeterministicP,
    synNodeGetDeterministicP,
    synGraphCompileP,
    synGraphCreateP,
    synGraphCreateEagerP,
    synGraphDuplicateP,
    synGraphInferShapesP,
    synGraphDestroyP,
    synMemsetD32AsyncP,
    synMemsetD8AsyncP,
    synMemsetD16AsyncP,
    synHostMallocP,
    synHostFreeP,
    synHostMapP,
    synHostUnmapP,
    synDeviceMallocP,
    synDeviceFreeP,
    synTensorHandleCreateP,
    synTensorAssignToSectionP,
    synTensorSetSectionOffsetP,
    synTensorSetHostPtrP,
    synTensorSetQuantizationDataP,
    synTensorSetExternalP,
    synTensorSetGeometryExtP,
    synTensorSetGeometryP,
    synTensorSetDeviceDataTypeP,
    synTensorSetDeviceLayoutP,
    synTensorSetPermutationP,
    synTensorSetDeviceFullLayoutP,
    synTensorGetSectionP,
    synTensorSetAllowPermutationP,
    synTensorGetHostPtrP,
    synTensorGetQuantizationDataP,
    synTensorGetGeometryExtP,
    synTensorGetGeometryP,
    synTensorGetPermutationP,
    synTensorGetDeviceFullLayoutP,
    synTensorGetExternalP,
    synTensorGetDeviceDataTypeP,
    synTensorGetDeviceLayoutP,
    synTensorGetNameP,
    synTensorGetTypeP,
    synTPCLibraryGetVersionSizeP,
    synTPCLibraryGetVersionsP,
    synStreamSetAffinityP,
    synStreamGetAffinityP,
    synDeviceGetAffinityMaskRangeP,
    synDeviceGetNextStreamAffinity,
    synNodeSetUserParamsP,
    synNodeGetUserParamsP,
    synStreamCreateP,
    synStreamDestroyP,
    synSectionSetRMWP,
    synSectionGetRMWP,
    synRecipeSectionHostBuffersClear,
    synRecipeSerializeP,
    synRecipeDeSerializeP,
    synRecipeSectionGetPropP,
    synTensorGetAllowPermutationP,
    synProfilerQueryRequiredMemoryP,
    synProfilerSetUserBufferP,
    synProfilerStartP,
    synDeviceGetCountP,
    synDeviceGetCountByDeviceTypeP,
    synDeviceCountP,
    synGraphSetAttributeP,
    synGraphSetAttributesP,
    synGraphGetAttributeP,
    synGraphGetAttributesP,
    synDeviceGetModuleIDsP,
    synDeviceAcquireByDeviceTypeP,
    synDeviceAcquireByModuleIdP,
    synDeviceAcquireP,
    synDeviceSynchronizeP,
    synDeviceGetNameP,
    synStreamSynchronizeP,
    synEventSynchronizeP,
    synTensorRetrieveInfosByNameExtP,
    synTensorRetrievePersistentAmountP,
    synTensorRetrieveNamesP,
    synTensorRetrieveLaunchAmountP,
    synTensorRetrieveLaunchIdsP,
    synTensorRetrieveLaunchInfoByIdExtP,
    synNodeSetRoundingModeP,
    synNodeGetRoundingModeP,
    synGraphGetDeviceTypeP,
    synDeviceReleaseP,
    synDeviceGetMemoryInfoP,
    synDeviceGetInfoP,
    synDeviceGetAttributeP,
    synDeviceGetAttributeByModuleIdP,
    synDeviceTypeGetAttributeP,
    synConfigurationSetP,
    synConfigurationGetP,
    synDeviceGetPCIBusIdP,
    synProfilerStopP,
    synProfilerGetTraceP,
    synProfilerGetCurrentTimeNSP,
    synProfilerAddCustomMeasurementP,
    synProfilerAddCustomMeasurementArgsP,
    synProfilerAddCustomMeasurementArgsAndThreadP,
    synProfilerAddCustomEventP,

    LAST
};

inline constexpr auto enumNameSynApi = toStatArray<StatApiPoints>({
    { StatApiPoints::synLaunchP,                                        "synLaunch"                                     },
    { StatApiPoints::synLaunchWithExternalEventsP,                      "synLaunchWithExternalEvents"                   },
    { StatApiPoints::synStreamWaitEventP,                               "synStreamWaitEvent"                            },
    { StatApiPoints::synStreamQueryP,                                   "synStreamQuery"                                },
    { StatApiPoints::synEventCreateP,                                   "synEventCreate"                                },
    { StatApiPoints::synEventDestroyP,                                  "synEventDestroy"                               },
    { StatApiPoints::synEventRecordP,                                   "synEventRecord"                                },
    { StatApiPoints::synEventQueryP,                                    "synEventQuery"                                 },
    { StatApiPoints::synEventElapsedTimeP,                              "synEventElapsedTime"                           },
    { StatApiPoints::synEventMapTensorP,                                "synEventMapTensor"                             },
    { StatApiPoints::synTensorExtExtractExecutionOrderP,                "synTensorExtExtractExecutionOrder"             },
    { StatApiPoints::synRecipeDestroyP,                                 "synRecipeDestroy"                              },
    { StatApiPoints::synRecipeGetAttributeP,                            "synRecipeGetAttribute"                         },
    { StatApiPoints::synSectionCreateP,                                 "synSectionCreate"                              },
    { StatApiPoints::synSectionSetGroupP,                               "synSectionSetGroup"                            },
    { StatApiPoints::synSectionGetGroupP,                               "synSectionGetGroup"                            },
    { StatApiPoints::synSectionGetPersistentP,                          "synSectionGetPersistent"                       },
    { StatApiPoints::synSectionSetPersistentP,                          "synSectionSetPersistent"                       },
    { StatApiPoints::synSectionSetConstP,                               "synSectionSetConst"                            },
    { StatApiPoints::synSectionGetConstP,                               "synSectionGetConst"                            },
    { StatApiPoints::synSectionDestroyP,                                "synSectionDestroy"                             },
    { StatApiPoints::synWorkspaceGetSizeP,                              "synWorkspaceGetSize"                           },
    { StatApiPoints::synMemCopyAsyncMultipleP,                          "synMemCopyAsyncMultiple"                       },
    { StatApiPoints::synMemCopyAsyncP,                                  "synMemCopyAsync"                               },
    { StatApiPoints::synTensorCreateP,                                  "synTensorCreate"                               },
    { StatApiPoints::synConstTensorCreateP,                             "synConstTensorCreate"                          },
    { StatApiPoints::synTensorRetrieveIdsP,                             "synTensorRetrieveIds"                          },
    { StatApiPoints::synTensorDestroyP,                                 "synTensorDestroy"                              },
    { StatApiPoints::synNodeCreateP,                                    "synNodeCreate"                                 },
    { StatApiPoints::synNodeCreateWithIdP,                              "synNodeCreateWithId"                           },
    { StatApiPoints::synNodeTypeSetPrecisionP,                          "synNodeTypeSetPrecision"                       },
    { StatApiPoints::synNodeDependencySetP,                             "synNodeDependencySet"                          },
    { StatApiPoints::synNodeSetDeterministicP,                          "synNodeSetDeterministic"                       },
    { StatApiPoints::synNodeGetDeterministicP,                          "synNodeGetDeterministic"                       },
    { StatApiPoints::synGraphCompileP,                                  "synGraphCompile"                               },
    { StatApiPoints::synGraphCreateP,                                   "synGraphCreate"                                },
    { StatApiPoints::synGraphCreateEagerP,                              "synGraphCreateEager"                           },
    { StatApiPoints::synGraphDuplicateP,                                "synGraphDuplicate"                             },
    { StatApiPoints::synGraphInferShapesP,                              "synGraphInferShapes"                           },
    { StatApiPoints::synGraphDestroyP,                                  "synGraphDestroy"                               },
    { StatApiPoints::synMemsetD32AsyncP,                                "synMemsetD32Async"                             },
    { StatApiPoints::synMemsetD8AsyncP,                                 "synMemsetD8Async"                              },
    { StatApiPoints::synMemsetD16AsyncP,                                "synMemsetD16Async"                             },
    { StatApiPoints::synHostMallocP,                                    "synHostMalloc"                                 },
    { StatApiPoints::synHostFreeP,                                      "synHostFree"                                   },
    { StatApiPoints::synHostMapP,                                       "synHostMap"                                    },
    { StatApiPoints::synHostUnmapP,                                     "synHostUnmap"                                  },
    { StatApiPoints::synDeviceMallocP,                                  "synDeviceMalloc"                               },
    { StatApiPoints::synDeviceFreeP,                                    "synDeviceFree"                                 },
    { StatApiPoints::synTensorHandleCreateP,                            "synTensorHandleCreate"                         },
    { StatApiPoints::synTensorAssignToSectionP,                         "synTensorAssignToSection"                      },
    { StatApiPoints::synTensorSetSectionOffsetP,                        "synTensorSetSectionOffset"                     },
    { StatApiPoints::synTensorSetHostPtrP,                              "synTensorSetHostPtr"                           },
    { StatApiPoints::synTensorSetQuantizationDataP,                     "synTensorSetQuantizationData"                  },
    { StatApiPoints::synTensorSetExternalP,                             "synTensorSetExternal"                          },
    { StatApiPoints::synTensorSetGeometryExtP,                          "synTensorSetGeometryExt"                       },
    { StatApiPoints::synTensorSetGeometryP,                             "synTensorSetGeometry"                          },
    { StatApiPoints::synTensorSetDeviceDataTypeP,                       "synTensorSetDeviceDataType"                    },
    { StatApiPoints::synTensorSetDeviceLayoutP,                         "synTensorSetDeviceLayout"                      },
    { StatApiPoints::synTensorSetPermutationP,                          "synTensorSetPermutation"                       },
    { StatApiPoints::synTensorSetDeviceFullLayoutP,                     "synTensorSetDeviceFullLayout"                  },
    { StatApiPoints::synTensorGetSectionP,                              "synTensorGetSection"                           },
    { StatApiPoints::synTensorSetAllowPermutationP,                     "synTensorSetAllowPermutation"                  },
    { StatApiPoints::synTensorGetHostPtrP,                              "synTensorGetHostPtr"                           },
    { StatApiPoints::synTensorGetQuantizationDataP,                     "synTensorGetQuantizationData"                  },
    { StatApiPoints::synTensorGetGeometryExtP,                          "synTensorGetGeometryExt"                       },
    { StatApiPoints::synTensorGetGeometryP,                             "synTensorGetGeometry"                          },
    { StatApiPoints::synTensorGetPermutationP,                          "synTensorGetPermutation"                       },
    { StatApiPoints::synTensorGetDeviceFullLayoutP,                     "synTensorGetDeviceFullLayout"                  },
    { StatApiPoints::synTensorGetExternalP,                             "synTensorGetExternal"                          },
    { StatApiPoints::synTensorGetDeviceDataTypeP,                       "synTensorGetDeviceDataType"                    },
    { StatApiPoints::synTensorGetDeviceLayoutP,                         "synTensorGetDeviceLayout"                      },
    { StatApiPoints::synTensorGetNameP,                                 "synTensorGetName"                              },
    { StatApiPoints::synTensorGetTypeP,                                 "synTensorGetType"                              },
    { StatApiPoints::synTPCLibraryGetVersionSizeP,                      "synTPCLibraryGetVersionSize"                   },
    { StatApiPoints::synTPCLibraryGetVersionsP,                         "synTPCLibraryGetVersions"                      },
    { StatApiPoints::synStreamSetAffinityP,                             "synStreamSetAffinity"                          },
    { StatApiPoints::synStreamGetAffinityP,                             "synStreamGetAffinity"                          },
    { StatApiPoints::synDeviceGetAffinityMaskRangeP,                    "synDeviceGetAffinityMaskRange"                 },
    { StatApiPoints::synDeviceGetNextStreamAffinity,                    "synDeviceGetNextStreamAffinity"                },
    { StatApiPoints::synNodeSetUserParamsP,                             "synNodeSetUserParams"                          },
    { StatApiPoints::synNodeGetUserParamsP,                             "synNodeGetUserParams"                          },
    { StatApiPoints::synStreamCreateP,                                  "synStreamCreate"                               },
    { StatApiPoints::synStreamDestroyP,                                 "synStreamDestroy"                              },
    { StatApiPoints::synSectionSetRMWP,                                 "synSectionSetRMW"                              },
    { StatApiPoints::synSectionGetRMWP,                                 "synSectionGetRMW"                              },
    { StatApiPoints::synRecipeSectionHostBuffersClear,                  "synRecipeSectionHostBuffersClear"              },
    { StatApiPoints::synRecipeSerializeP,                               "synRecipeSerialize"                            },
    { StatApiPoints::synRecipeDeSerializeP,                             "synRecipeDeSerialize"                          },
    { StatApiPoints::synRecipeSectionGetPropP,                          "synRecipeSectionGetProp"                       },
    { StatApiPoints::synTensorGetAllowPermutationP,                     "synTensorGetAllowPermutation"                  },
    { StatApiPoints::synProfilerQueryRequiredMemoryP,                   "synProfilerQueryRequiredMemory"                },
    { StatApiPoints::synProfilerSetUserBufferP,                         "synProfilerSetUserBuffer"                      },
    { StatApiPoints::synProfilerStartP,                                 "synProfilerStart"                              },
    { StatApiPoints::synDeviceGetCountP,                                "synDeviceGetCount"                             },
    { StatApiPoints::synDeviceGetCountByDeviceTypeP,                    "synDeviceGetCountByDeviceType"                 },
    { StatApiPoints::synDeviceCountP,                                   "synDeviceCount"                                },
    { StatApiPoints::synGraphSetAttributeP,                             "synGraphSetAttribute"                          },
    { StatApiPoints::synGraphSetAttributesP,                            "synGraphSetAttributes"                         },
    { StatApiPoints::synGraphGetAttributeP,                             "synGraphGetAttribute"                          },
    { StatApiPoints::synGraphGetAttributesP,                            "synGraphGetAttributes"                         },
    { StatApiPoints::synDeviceGetModuleIDsP,                            "synDeviceGetModuleIDs"                         },
    { StatApiPoints::synDeviceAcquireByDeviceTypeP,                     "synDeviceAcquireByDeviceType"                  },
    { StatApiPoints::synDeviceAcquireByModuleIdP,                       "synDeviceAcquireByModuleId"                    },
    { StatApiPoints::synDeviceAcquireP,                                 "synDeviceAcquire"                              },
    { StatApiPoints::synDeviceSynchronizeP,                             "synDeviceSynchronize"                          },
    { StatApiPoints::synDeviceGetNameP,                                 "synDeviceGetName"                              },
    { StatApiPoints::synStreamSynchronizeP,                             "synStreamSynchronize"                          },
    { StatApiPoints::synEventSynchronizeP,                              "synEventSynchronize"                           },
    { StatApiPoints::synTensorRetrieveInfosByNameExtP,                  "synTensorRetrieveInfosByNameExt"               },
    { StatApiPoints::synTensorRetrievePersistentAmountP,                "synTensorRetrievePersistentAmount"             },
    { StatApiPoints::synTensorRetrieveNamesP,                           "synTensorRetrieveNames"                        },
    { StatApiPoints::synTensorRetrieveLaunchAmountP,                    "synTensorRetrieveLaunchAmount"                 },
    { StatApiPoints::synTensorRetrieveLaunchIdsP,                       "synTensorRetrieveLaunchIds"                    },
    { StatApiPoints::synTensorRetrieveLaunchInfoByIdExtP,               "synTensorRetrieveLaunchInfoByIdExt"            },
    { StatApiPoints::synNodeSetRoundingModeP,                           "synNodeSetRoundingMode"                        },
    { StatApiPoints::synNodeGetRoundingModeP,                           "synNodeGetRoundingMode"                        },
    { StatApiPoints::synGraphGetDeviceTypeP,                            "synGraphGetDeviceType"                         },
    { StatApiPoints::synDeviceReleaseP,                                 "synDeviceRelease"                              },
    { StatApiPoints::synDeviceGetMemoryInfoP,                           "synDeviceGetMemoryInfo"                        },
    { StatApiPoints::synDeviceGetInfoP,                                 "synDeviceGetInfo"                              },
    { StatApiPoints::synDeviceGetAttributeP,                            "synDeviceGetAttribute"                         },
    { StatApiPoints::synDeviceGetAttributeByModuleIdP,                  "synDeviceGetAttributeByModuleIdP"              },
    { StatApiPoints::synDeviceTypeGetAttributeP,                        "synDeviceTypeGetAttribute"                     },
    { StatApiPoints::synConfigurationSetP,                              "synConfigurationSet"                           },
    { StatApiPoints::synConfigurationGetP,                              "synConfigurationGet"                           },
    { StatApiPoints::synDeviceGetPCIBusIdP,                             "synDeviceGetPCIBusId"                          },
    { StatApiPoints::synProfilerStopP,                                  "synProfilerStop"                               },
    { StatApiPoints::synProfilerGetTraceP,                              "synProfilerGetTrace"                           },
    { StatApiPoints::synProfilerGetCurrentTimeNSP,                      "synProfilerGetCurrentTimeNS"                   },
    { StatApiPoints::synProfilerAddCustomMeasurementP,                  "synProfilerAddCustomMeasurement"               },
    { StatApiPoints::synProfilerAddCustomMeasurementArgsP,              "synProfilerAddCustomMeasurementArgs"           },
    { StatApiPoints::synProfilerAddCustomMeasurementArgsAndThreadP,     "synProfilerAddCustomMeasurementArgsAndThread"  },
    { StatApiPoints::synProfilerAddCustomEventP,                        "synProfilerAddCustomEvent"                     },
     });
