op {
  name: "Expand dims"
type {
    name: "T"
    definition: "tensor(float32), tensor(bfloat16), tensor(int32), tensor(int16), tensor(int8), tensor(int4)"
    description: "A 1D, 2D, 3D, or 4D tensor with the elements of type specified in the definition."
}
type {
    name: "U"
    definition: "tensor(float32), tensor(bfloat16), tensor(int32), tensor(int16), tensor(int8), tensor(int4)"
    description: "A 2D, 3D, 4D, or 5D tensor with the elements of type specified in the definition."
}
input {
    name: "Input_Tensor"
    type: "T"
    description: "Input Tensor of type ``T``."
  }
output {
    name: "Output_Tensor"
    type: "U"
    description: "Output_Tensor tensor is the output of the *Expand dims* operation."
}
c_structure: "struct synExpandDimsParams;"
attr {
    name: "axis"
    type: "unsigned int"
    description: "The axis after which add a dimension of size 1"
  }
  summary: "This node creates a tensor of size *D+1* from a tensor of size *D* by adding size 1 at the axis parameter.\n"
           "Example- input of sizes [128,256,12] expanded with *axis=1* expects output of sizes [128,256,1,12]"
  guid: "expand_dims"
}
