op {
  name: "Memset"
  type {
    name: "T"
    definition: "tensor(float32), tensor(bfloat16), tensor(int32), tensor(int16), tensor(int8), tensor(int4)"
    description: "A 1D, 2D, 3D, 4D or 5D tensor with the elements of type specified in the definition."
  }
  input {
    name: "Shape tensor describing output shape"
    type: "T"
    description: "Input Tensor of type ``T`` with dimensionality 1-5D."
  }
  output {
    name: "The destination tensor"
    type: "T"
    description: ""
  }
  summary: "Initializes the destination tensor to 0"
  description: ""
  constraints: ["int4 supported platform: Greco"]
  guid: "memset"
}
