op {
  name: "Split"
   type {
    name: "T"
    definition: "tensor(float32), tensor(bfloat16), tensor(int32), tensor(int16), tensor(int8), tensor(int4)"
    description: "A 1D, 2D, 3D, 4D or 5D tensor with the elements of type specified in the definition."
  }
   c_structure: "struct synSplitParams;"
  attr {
    name: "axis"
    type: "unsigned"
    description: "The split dim."
  }

  input {
    name: "The tensor to split"
    type: "T"
    description: "Input Tensor of type ``T`` with dimensionality 1-5D."
  }
  output {
    name: "out_0"
    type: "T"
    description: "The first part of the input"
  }
  output {
    name: "out_1"
    type: "T"
    description: "The second part of the input"
  }
  output {
    name: "out_n"
    type: "T"
    description: "The last part of the input"
  }
  summary: "Split a tensor into a list of tensors"
  description: "The split is done, along the specified 'axis'. Lengths of the parts are specified"
               "in the sizes of the output parts"
  constraints: ["Input and out tensors must have the same data type."
                "Aggregate size along aggregate dimension must match input tensor size in that dimension"
                "Shape of output tensors in all dimenstion except the split dimension."
                "int4 supported platform: Greco"]
  guid: "split"
}
