orchestratorConfig:
  cron: "H H/3 * * *"
  testConfig:
    - testToLaunch: synapse/Tests/Test_synapse_gaudi_asic_synapse_tests
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_asic_synapse_tests
    - testToLaunch: synapse/Tests/Test_synapse_gaudi_sim_models_compilation
    - testToLaunch: synapse/Tests/Test_synapse_gaudi_hls_asic_ci_perf_gemm
    - testToLaunch: coral_sim/Tests/Test_coral_sim_gaudi2_sim_external_test
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_engines_fw_test_0
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_engines_fw_test_1
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_sim_engines_fw_test
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_sim_scal_test
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_scal_test
    - testToLaunch: synapse/Tests/Test_synapse_gaudi_sim_mme_tests
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_mme_tests
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_sim_mme_tests
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_models_compilation
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_pipeline_management_models_compilation
    - testToLaunch: mlperf_inference/Tests/Test_mlperf_inference_gaudi2_asic_8cards_promote
      silentMode: true
    - testToLaunch: synapse/Tests/Test_synapse_gaudi_hls_asic_rec_topology_perf
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_asic_rec_topology_perf
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_asic_rec_topology_perf
    - testToLaunch: synapse/Tests/Test_synapse_gaudi_hls_asic_rec_topology_accuracy
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_asic_rec_topology_accuracy
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_rec_topology_accuracy
    - testToLaunch: synapse/Tests/Test_synapse_gaudi_asic_synapse_gc_tests
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_asic_synapse_gc_tests
    - testToLaunch: synapse/Tests/Test_synapse_gaudi_sim_8cards_multi_device
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_sim_arc_mode3_test_group_0
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_sim_arc_mode3_gc_test_group_0
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_sim_arc_mode3_gc_test_group_1
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_sim_arc_mode3_gc_test_group_2
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_sim_arc_mode3_gc_test_group_3
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_sim_arc_mode3_gc_test_group_4
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_sim_arc_mode3_gc_test_group_5
    - testToLaunch: synapse/Tests/Test_synapse_gaudi_sim_synapse_tests_group_0
    - testToLaunch: synapse/Tests/Test_synapse_gaudi_sim_synapse_gc_tests_group_0
    - testToLaunch: synapse/Tests/Test_synapse_gaudi_sim_synapse_gc_tests_group_1
    - testToLaunch: synapse/Tests/Test_synapse_gaudi_sim_synapse_gc_tests_group_2
    - testToLaunch: synapse/Tests/Test_synapse_gaudi_sim_synapse_gc_tests_group_3
    - testToLaunch: synapse/Tests/Test_synapse_gaudi_sim_synapse_gc_tests_group_4
    - testToLaunch: synapse/Tests/Test_synapse_gaudi_sim_synapse_gc_tests_group_5
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_sim_synapse_gc_tests_group_6
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_synapse_gc_tests_group_6
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_synapse_tests_group_0
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_synapse_gc_tests_group_0
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_synapse_gc_tests_group_1
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_synapse_gc_tests_group_2
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_synapse_gc_tests_group_3
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_synapse_gc_tests_group_4
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_synapse_gc_tests_group_5
    - testToLaunch: synapse/Tests/Test_synapse_cpu_graph_optimizer_tests
    - testToLaunch: synapse/Tests/Test_synapse_cpu_runtime_unit_tests
    - testToLaunch: synapse_profiler/Tests/Test_synapse_profiler_cpu_qman_parser
    - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi_asic_promote_training_suite
    - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_asic_promote_training_suite
    - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi3_sim_promote_training_suite
    - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi_asic_topology_functionality
    - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_asic_topology_functionality
    - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi_sim_distributed
    - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_sim_distributed
    - testToLaunch: synapse_gc_tpc_tests/Tests/Test_synapse_gc_tpc_tests_gaudi_asic_promote_training_suite
    - testToLaunch: synapse_gc_tpc_tests/Tests/Test_synapse_gc_tpc_tests_gaudi2_asic_promote_training_suite
    - testToLaunch: synapse_gc_tpc_tests/Tests/Test_synapse_gc_tpc_tests_gaudi3_sim_promote_training_suite
    - testToLaunch: synapse_gc_tpc_tests/Tests/Test_synapse_gc_tpc_tests_gaudi3_sim_promote_training_suite_2
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_resnet50_batch64_bf16
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_resnet50_batch64_float32
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_asic_engines_fw_test
    - testToLaunch: deepspeed_fork/Tests/Test_deepspeed_fork_gaudi_sim_test
    - testToLaunch: deepspeed_fork/Tests/Test_deepspeed_fork_gaudi2_sim_test
    - testToLaunch: deepspeed_fork/Tests/Test_deepspeed_fork_gaudi_hls_asic_unit_tests_promote
    - testToLaunch: deepspeed_fork/Tests/Test_deepspeed_fork_gaudi2_asic_unit_tests_promote
    - testToLaunch: deepspeed_fork/Tests/Test_deepspeed_fork_gaudi2_asic_8cards_test
    - testToLaunch: deepspeed_examples_fork/Tests/Test_deepspeed_examples_fork_gaudi2_asic_8cards_test
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_sim_models_compilation
    - testToLaunch: synapse_profiler/Tests/Test_synapse_profiler_gaudi_asic_swtools_test
    - testToLaunch: synapse_profiler/Tests/Test_synapse_profiler_gaudi2_asic_swtools_test
    - testToLaunch: habanaqa_synapse/Tests/Test_habanaqa_synapse_gaudi2_asic_synapse_test_suit
    - testToLaunch: habanaqa_inference/Tests/Test_habanaqa_inference_gaudi2_asic_bert_suite
    - testToLaunch: habanaqa_inference/Tests/Test_habanaqa_inference_gaudi2_asic_resnet50_suite
    - testToLaunch: habanaqa_inference/Tests/Test_habanaqa_inference_gaudi2_asic_llama7b_hqt_suite
    - testToLaunch: habanaqa_inference/Tests/Test_habanaqa_inference_gaudi2_asic_8cards_llama70b_hqt_ptq_4096t_suite
    - testToLaunch: habanaqa_hccl/Tests/Test_habanaqa_hccl_gaudi_sim_sanity_tests
    - testToLaunch: hcl/Tests/Test_hcl_gaudi_sim_hcl_tests_8
    - testToLaunch: hcl/Tests/Test_hcl_gaudi2_sim_HCL_Loopback_tests
    - testToLaunch: hcl/Tests/Test_hcl_gaudi3_sim_HCL_Loopback_tests
    - testToLaunch: hcl/Tests/Test_hcl_gaudi2_sim_rank_8
    - testToLaunch: hcl/Tests/Test_hcl_gaudi3_sim_rank_8
    - testToLaunch: hcl/Tests/Test_hcl_gaudi_sim_HCL_scaleout
    - testToLaunch: hcl/Tests/Test_hcl_gaudi2_sim_HCL_scaleout
    - testToLaunch: hcl/Tests/Test_hcl_gaudi3_sim_HCL_scaleout
    # hcl
    - testToLaunch: habanaqa_hccl/Tests/Test_habanaqa_hccl_gaudi_sim_sanity_tests
  sanitizerConfig:
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_sim_arc_mode3_test_group_0
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_sim_arc_mode3_gc_test_group_0
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_sim_arc_mode3_gc_test_group_1
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_sim_arc_mode3_gc_test_group_2
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_sim_arc_mode3_gc_test_group_3
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_sim_arc_mode3_gc_test_group_4
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_sim_arc_mode3_gc_test_group_5
    - testToLaunch: synapse/Tests/Test_synapse_gaudi_sim_synapse_tests_group_0
    - testToLaunch: synapse/Tests/Test_synapse_gaudi_sim_synapse_gc_tests_group_0
    - testToLaunch: synapse/Tests/Test_synapse_gaudi_sim_synapse_gc_tests_group_1
    - testToLaunch: synapse/Tests/Test_synapse_gaudi_sim_synapse_gc_tests_group_2
    - testToLaunch: synapse/Tests/Test_synapse_gaudi_sim_synapse_gc_tests_group_4
    - testToLaunch: synapse/Tests/Test_synapse_gaudi_sim_synapse_gc_tests_group_5
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_synapse_tests_group_0
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_synapse_gc_tests_group_0
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_synapse_gc_tests_group_1
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_synapse_gc_tests_group_2
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_synapse_gc_tests_group_3
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_synapse_gc_tests_group_4
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_synapse_gc_tests_group_5
    - testToLaunch: synapse/Tests/Test_synapse_cpu_graph_optimizer_tests
    - testToLaunch: habana_quantization_toolkit/Tests/Test_habana_quantization_toolkit_gaudi2_asic_test
      silentMode: true
  codeCoverageConfig:
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_sim_arc_mode3_test_group_0
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_sim_arc_mode3_gc_test_group_0
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_sim_arc_mode3_gc_test_group_1
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_sim_arc_mode3_gc_test_group_2
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_sim_arc_mode3_gc_test_group_3
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_sim_arc_mode3_gc_test_group_4
    - testToLaunch: synapse/Tests/Test_synapse_gaudi2_sim_arc_mode3_gc_test_group_5
    - testToLaunch: synapse/Tests/Test_synapse_gaudi_sim_synapse_tests_group_0
    - testToLaunch: synapse/Tests/Test_synapse_gaudi_sim_synapse_gc_tests_group_0
    - testToLaunch: synapse/Tests/Test_synapse_gaudi_sim_synapse_gc_tests_group_1
    - testToLaunch: synapse/Tests/Test_synapse_gaudi_sim_synapse_gc_tests_group_2
    - testToLaunch: synapse/Tests/Test_synapse_gaudi_sim_synapse_gc_tests_group_3
    - testToLaunch: synapse/Tests/Test_synapse_gaudi_sim_synapse_gc_tests_group_4
    - testToLaunch: synapse/Tests/Test_synapse_gaudi_sim_synapse_gc_tests_group_5
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_synapse_tests_group_0
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_synapse_gc_tests_group_0
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_synapse_gc_tests_group_1
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_synapse_gc_tests_group_2
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_synapse_gc_tests_group_3
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_synapse_gc_tests_group_4
    - testToLaunch: synapse/Tests/Test_synapse_gaudi3_sim_synapse_gc_tests_group_5
    - testToLaunch: synapse/Tests/Test_synapse_cpu_graph_optimizer_tests
    - testToLaunch: hcl/Tests/Test_hcl_gaudi3_sim_rank_8
    - testToLaunch: hcl/Tests/Test_hcl_gaudi2_sim_rank_8
  coverityConfig:
stepConfig:
  jobTimeout: '250'
